# Generated by Django 4.1.1 on 2022-10-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0003_category_alter_game_platform_game_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheat_codes', models.CharField(max_length=512)),
                ('finished', models.BooleanField()),
                ('play_time', models.TimeField()),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games_app.game')),
            ],
        ),
    ]
