# Generated by Django 4.1.1 on 2022-10-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('my_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorapp.myorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='myorder',
            name='product',
            field=models.ManyToManyField(through='shorapp.ProductMyOrder', to='shorapp.product'),
        ),
    ]
