# Generated by Django 4.1.1 on 2022-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chleb', models.BooleanField(default=False)),
                ('woda', models.BooleanField(default=False)),
                ('maslo', models.BooleanField(default=False)),
                ('szynka', models.BooleanField(default=False)),
            ],
        ),
    ]
