# Generated by Django 4.1.1 on 2022-10-07 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='host_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_set', to='football_app.team'),
        ),
    ]
